# syntax=docker/dockerfile:1

FROM node:lts-alpine

WORKDIR /app
ENV NODE_ENV development
ENV PORT 80

COPY package.json package-lock.json ./
RUN npm ci
COPY . .

EXPOSE 80
CMD [ \
    "npm", "run", "dev", \
    "--host", "frontend"
]
