# syntax=docker/dockerfile:1

FROM node:lts-alpine

WORKDIR /app
ENV NODE_ENV development
ENV PORT 80

COPY package.json package-lock.json svelte.config.js vite.config.ts ./
RUN npm ci
COPY . .

EXPOSE 80 81
CMD [ \
    "npm", "run", "dev", "--", \
    "--host", "frontend" \
]
