version: "3.9"

services:
  api:
    container_name: fastapi
    build: api
    environment:
      UVICORN_RELOAD: true
    networks:
      - bridge
    volumes:
      - files:/app/files
      - ./api/src:/app/src

  web:
    container_name: nginx
    build: www
    environment:
      NODE_ENV: development
    networks:
      - bridge
    ports:
      - "80:80"
      - "443:443"

networks:
  bridge:
    driver: bridge

volumes:
  files:
    name: fileforest-files
