version: "3.9"

services:
  backend:
    container_name: backend
    build: backend
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api
      - traefik.http.routers.backend.entrypoints=web
      - traefik.http.routers.backend.rule=Host(`localhost`) && PathPrefix(`/api`)
      - traefik.http.routers.backend.middlewares=backend-stripprefix
    environment:
      UVICORN_RELOAD: "true"
    networks:
      - bridge
    volumes:
      - files:/app/files
      - ./backend/src:/app/src

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile-dev
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.entrypoints=web
      - traefik.http.routers.frontend.rule=Host(`localhost`)
      - traefik.http.routers.hmr.entrypoints=hmr
      - traefik.http.routers.hmr.rule=Host(`localhost`)
    networks:
      - bridge
    volumes:
      - ./frontend/src:/app/src

  proxy:
    container_name: proxy
    image: traefik:v2.8
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.hmr.address=:81
    ports:
      - "80:80"
      - "81:81"
      - "8080:8080"
    networks:
      - bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro


networks:
  bridge:
    driver: bridge

volumes:
  files:
    name: fileforest-files
